123 lesson

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,4 +19,11 @@ jobs:
           host: ${{ secrets.REMOTE_HOST }}
           username: ${{ secrets.REMOTE_USER }}
           password: ${{ secrets.REMOTE_PASSWORD }}
-          script: .deploy/deploy.sh
+          script: |
+            if [ -f ~/production-project/.deploy/deploy.sh ]; then
+              chmod +x ~/production-project/.deploy/deploy.sh
+              ~/production-project/.deploy/deploy.sh
+            else
+              ls -la ~/production-project/.deploy
+              echo "Deployment script not found!"
+              exit 1
